# Generated by Django 5.2.1 on 2026-01-20 10:17

import django.db.models.deletion
import quizzes.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_question_questionoption_quiz_question_quiz_and_more'),
        ('quizzes', '0002_quiz_is_published_alter_quizattempt_graded_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeroption',
            name='question',
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['question__order'], 'verbose_name': 'إجابة', 'verbose_name_plural': 'إجابات'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'سؤال', 'verbose_name_plural': 'أسئلة'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name': 'كويز', 'verbose_name_plural': 'كويزات'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-started_at'], 'verbose_name': 'محاولة كويز', 'verbose_name_plural': 'محاولات الكويز'},
        ),
        migrations.RemoveIndex(
            model_name='quiz',
            name='quizzes_qui_course__514df3_idx',
        ),
        migrations.RemoveField(
            model_name='question',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='randomize_questions',
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(blank=True, verbose_name='نص الإجابة'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizattempt', verbose_name='المحاولة'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True, verbose_name='صحيحة'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='points_earned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة المكتسبة'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.question', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_option',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الخيار المختار'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='الإجابة الصحيحة للأسئلة الاختيارية أو صح/خطأ', max_length=255, null=True, verbose_name='الإجابة الصحيحة'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='قائمة الخيارات للأسئلة الاختيارية (JSON)', verbose_name='الخيارات'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[quizzes.validators.validate_positive_points], verbose_name='الدرجة'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'اختيار من متعدد'), ('true_false', 'صح/خطأ'), ('essay', 'مقالي')], max_length=20, verbose_name='نوع السؤال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz', verbose_name='الكويز'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='نص السؤال'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course', verbose_name='الكورس'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف الكويز'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='grading_method',
            field=models.CharField(choices=[('highest', 'أعلى درجة'), ('last', 'آخر محاولة')], default='highest', max_length=10, verbose_name='طريقة التقييم'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text='مطلوب لإكمال الكورس', verbose_name='إجباري'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=False, help_text='هل الكويز منشور ومتاح للطلاب', verbose_name='منشور'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1, help_text='الحد الأقصى لعدد المحاولات المسموح بها', validators=[quizzes.validators.validate_max_attempts], verbose_name='أقصى عدد للمحاولات'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='passing_grade',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), help_text='أقل درجة للنجاح (0-100)', max_digits=5, validators=[quizzes.validators.validate_passing_grade], verbose_name='درجة النجاح'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='الوقت المحدد للكويز بالدقائق (فارغ = لا يوجد حد)', null=True, validators=[quizzes.validators.validate_time_limit], verbose_name='الوقت المحدد بالدقائق'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان الكويز'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(verbose_name='رقم المحاولة'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت التصحيح'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='graded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['teacher', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='مصحح بواسطة'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='passed',
            field=models.BooleanField(blank=True, null=True, verbose_name='ناجح'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz', verbose_name='الكويز'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='الدرجة من 100', max_digits=5, null=True, verbose_name='الدرجة'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت البدء'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'قيد التنفيذ'), ('submitted', 'تم التقديم'), ('graded', 'تم التصحيح'), ('timed_out', 'انتهى الوقت')], default='in_progress', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes_quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت التقديم'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='time_taken_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='الوقت المستغرق بالثواني'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['course', 'is_published'], name='quizzes_qui_course__62ace5_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'student'], name='quizzes_qui_quiz_id_68c200_idx'),
        ),
        migrations.DeleteModel(
            name='AnswerOption',
        ),
    ]
