# Generated by Django 5.2.1 on 2026-01-20 14:56

import django.db.models.deletion
import quizzes.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_question_questionoption_quiz_question_quiz_and_more'),
        ('quizzes', '0003_remove_answeroption_question_alter_answer_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['question__order'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-started_at'], 'verbose_name': 'Quiz Attempt', 'verbose_name_plural': 'Quiz Attempts'},
        ),
        migrations.RemoveIndex(
            model_name='quiz',
            name='quizzes_qui_course__62ace5_idx',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.AddField(
            model_name='quiz',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes_quizapp', related_query_name='quizzes_quizapp', to='courses.lecture', verbose_name='Lecture'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(blank=True, verbose_name='Answer Text'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizattempt', verbose_name='Attempt'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is Correct'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='points_earned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Points Earned'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_option',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Selected Option'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='Correct answer for multiple choice or true/false questions', max_length=255, null=True, verbose_name='Correct Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='List of options for multiple choice questions (JSON)', verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[quizzes.validators.validate_positive_points], verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('essay', 'Essay')], max_length=20, verbose_name='Question Type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, verbose_name='Quiz Description'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='grading_method',
            field=models.CharField(choices=[('highest', 'Highest Score'), ('last', 'Last Attempt')], default='highest', max_length=10, verbose_name='Grading Method'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text='Required to complete the course', verbose_name='Mandatory'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether the quiz is published and available to students', verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of allowed attempts', validators=[quizzes.validators.validate_max_attempts], verbose_name='Maximum Attempts'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='passing_grade',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), help_text='Minimum score to pass (0-100)', max_digits=5, validators=[quizzes.validators.validate_passing_grade], verbose_name='Passing Grade'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Quiz time limit in minutes (empty = no limit)', null=True, validators=[quizzes.validators.validate_time_limit], verbose_name='Time Limit (minutes)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Quiz Title'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(verbose_name='Attempt Number'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Graded At'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='graded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['teacher', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Graded By'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='passed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Passed'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Score out of 100', max_digits=5, null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Started At'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('timed_out', 'Timed Out')], default='in_progress', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes_quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submitted At'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='time_taken_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Time Taken (seconds)'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['lecture', 'is_published'], name='quizzes_qui_lecture_41abf4_idx'),
        ),
    ]
