# Generated by Django 5.2.1 on 2026-01-18 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecture_type',
            field=models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('quiz', 'Quiz'), ('assignment', 'Assignment')], db_index=True, default='video', max_length=20),
        ),
        migrations.AddField(
            model_name='lecture',
            name='prerequisite',
            field=models.ForeignKey(blank=True, help_text='Lecture that must be completed before this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_lectures', to='courses.lecture'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(limit_choices_to=models.Q(('role', 'teacher'), ('role', 'admin'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
