# Generated by Django 6.0.1 on 2026-01-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_question_questionoption_quiz_question_quiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturefile',
            name='file',
            field=models.FileField(upload_to='private_media/courses/lectures/files/'),
        ),
    ]
