# Generated by Django 5.2.1 on 2026-01-16 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.PositiveIntegerField(db_index=True, help_text='ID of the wallet in the payments app', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_reference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet Reference',
                'verbose_name_plural': 'Wallet References',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('role_changed', 'Role Changed'), ('course_created', 'Course Created'), ('course_approved', 'Course Approved'), ('course_rejected', 'Course Rejected'), ('course_deleted', 'Course Deleted'), ('course_edited', 'Course Edited'), ('ownership_transferred', 'Ownership Transferred'), ('wallet_deposit', 'Wallet Deposit'), ('wallet_withdrawal', 'Wallet Withdrawal'), ('purchase', 'Purchase'), ('refund', 'Refund'), ('recharge_code_used', 'Recharge Code Used'), ('manual_deposit', 'Manual Deposit'), ('quiz_attempt', 'Quiz Attempt'), ('quiz_graded', 'Quiz Graded'), ('quiz_deleted', 'Quiz Deleted'), ('admin_action', 'Admin Action'), ('system_event', 'System Event')], db_index=True, max_length=50)),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the action (required for some admin actions)', null=True)),
                ('object_type', models.CharField(blank=True, help_text='Type of object affected (e.g., "Course", "Payment", "Quiz")', max_length=100, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the object affected', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'action_type'], name='users_audit_created_2a3805_idx'), models.Index(fields=['actor', '-created_at'], name='users_audit_actor_i_fea760_idx'), models.Index(fields=['object_type', 'object_id'], name='users_audit_object__f792c7_idx')],
            },
        ),
    ]
